// This file will be auto-generated by `supabase gen types typescript`
// For now, define the initial schema types manually

export interface Database {
  public: {
    Tables: {
      api_call_log: {
        Row: {
          id: string
          provider: string
          endpoint: string
          method: string
          status_code: number | null
          response_time_ms: number | null
          tokens_used: number | null
          prompt_tokens: number | null
          completion_tokens: number | null
          cost_usd: number | null
          is_success: boolean
          error_message: string | null
          metadata: Record<string, unknown>
          user_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          provider?: string
          endpoint?: string
          method?: string
          status_code?: number | null
          response_time_ms?: number | null
          tokens_used?: number | null
          prompt_tokens?: number | null
          completion_tokens?: number | null
          cost_usd?: number | null
          is_success?: boolean
          error_message?: string | null
          metadata?: Record<string, unknown>
          user_id?: string | null
          created_at?: string
        }
        Update: {
          provider?: string
          endpoint?: string
          method?: string
          status_code?: number | null
          response_time_ms?: number | null
          tokens_used?: number | null
          prompt_tokens?: number | null
          completion_tokens?: number | null
          cost_usd?: number | null
          is_success?: boolean
          error_message?: string | null
          metadata?: Record<string, unknown>
        }
        Relationships: []
      }
      platform_api_configs: {
        Row: {
          id: string
          provider: string
          display_name: string
          api_key: string | null
          base_url: string | null
          is_active: boolean
          config: Record<string, unknown>
          test_status: string
          last_tested_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          provider: string
          display_name: string
          api_key?: string | null
          base_url?: string | null
          is_active?: boolean
          config?: Record<string, unknown>
          test_status?: string
          last_tested_at?: string | null
        }
        Update: {
          display_name?: string
          api_key?: string | null
          base_url?: string | null
          is_active?: boolean
          config?: Record<string, unknown>
          test_status?: string
          last_tested_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      admin_config: {
        Row: {
          key: string
          value: Record<string, unknown>
          updated_at: string
        }
        Insert: {
          key: string
          value: Record<string, unknown>
          updated_at?: string
        }
        Update: {
          key?: string
          value?: Record<string, unknown>
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          default_organization_id: string | null
          is_superuser: boolean
          dashboard_mode: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          default_organization_id?: string | null
          is_superuser?: boolean
          dashboard_mode?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          default_organization_id?: string | null
          is_superuser?: boolean
          dashboard_mode?: string
          updated_at?: string
        }
        Relationships: []
      }
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          plan_tier: 'solo' | 'team' | 'enterprise'
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          trial_ends_at: string | null
          seat_limit: number
          app_limit: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          plan_tier?: 'solo' | 'team' | 'enterprise'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          trial_ends_at?: string | null
          seat_limit?: number
          app_limit?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          slug?: string
          plan_tier?: 'solo' | 'team' | 'enterprise'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          trial_ends_at?: string | null
          seat_limit?: number
          app_limit?: number
          updated_at?: string
        }
        Relationships: []
      }
      organization_members: {
        Row: {
          id: string
          organization_id: string
          user_id: string
          role: 'owner' | 'admin' | 'member' | 'viewer'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          user_id: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          created_at?: string
          updated_at?: string
        }
        Update: {
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          updated_at?: string
        }
        Relationships: []
      }
      invitations: {
        Row: {
          id: string
          organization_id: string
          email: string
          role: 'owner' | 'admin' | 'member' | 'viewer'
          token: string
          expires_at: string
          accepted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          email: string
          role?: 'owner' | 'admin' | 'member' | 'viewer'
          token: string
          expires_at: string
          accepted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          accepted_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      apps: {
        Row: {
          id: string
          organization_id: string
          platform: 'ios' | 'android'
          store_id: string
          name: string
          icon_url: string | null
          developer: string | null
          category: string | null
          current_version: string | null
          added_at: string
          is_active: boolean
          optimization_goal: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          platform: 'ios' | 'android'
          store_id: string
          name: string
          icon_url?: string | null
          developer?: string | null
          category?: string | null
          current_version?: string | null
          added_at?: string
          is_active?: boolean
          optimization_goal?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          icon_url?: string | null
          developer?: string | null
          category?: string | null
          current_version?: string | null
          is_active?: boolean
          optimization_goal?: string
          updated_at?: string
        }
        Relationships: []
      }
      keywords: {
        Row: {
          id: string
          organization_id: string
          app_id: string
          text: string
          country: string
          is_tracked: boolean
          added_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          app_id: string
          text: string
          country?: string
          is_tracked?: boolean
          added_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          text?: string
          country?: string
          is_tracked?: boolean
          updated_at?: string
        }
        Relationships: []
      }
      keyword_ranks_daily: {
        Row: {
          id: string
          keyword_id: string
          date: string
          rank: number | null
          impressions_estimate: number | null
          search_volume: number | null
          difficulty: number | null
          kei: number | null
          created_at: string
        }
        Insert: {
          id?: string
          keyword_id: string
          date: string
          rank?: number | null
          impressions_estimate?: number | null
          search_volume?: number | null
          difficulty?: number | null
          kei?: number | null
          created_at?: string
        }
        Update: {
          rank?: number | null
          impressions_estimate?: number | null
          search_volume?: number | null
          difficulty?: number | null
          kei?: number | null
        }
        Relationships: []
      }
      competitors: {
        Row: {
          id: string
          app_id: string
          competitor_app_id: string
          added_at: string
          created_at: string
        }
        Insert: {
          id?: string
          app_id: string
          competitor_app_id: string
          added_at?: string
          created_at?: string
        }
        Update: Record<string, never>
        Relationships: []
      }
      reviews: {
        Row: {
          id: string
          app_id: string
          store_review_id: string
          rating: number
          title: string | null
          body: string | null
          author: string | null
          country: string | null
          version: string | null
          reviewed_at: string | null
          reply_body: string | null
          reply_at: string | null
          sentiment_score: number | null
          cluster_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          app_id: string
          store_review_id: string
          rating: number
          title?: string | null
          body?: string | null
          author?: string | null
          country?: string | null
          version?: string | null
          reviewed_at?: string | null
          reply_body?: string | null
          reply_at?: string | null
          sentiment_score?: number | null
          cluster_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          rating?: number
          title?: string | null
          body?: string | null
          reply_body?: string | null
          reply_at?: string | null
          sentiment_score?: number | null
          cluster_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      api_keys: {
        Row: {
          id: string
          organization_id: string
          name: string
          prefix: string
          hashed_key: string
          last_used_at: string | null
          created_by: string
          revoked_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          name: string
          prefix: string
          hashed_key: string
          last_used_at?: string | null
          created_by: string
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          last_used_at?: string | null
          revoked_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      app_metadata_snapshots: {
        Row: {
          id: string
          app_id: string
          locale: string
          title: string | null
          subtitle: string | null
          description: string | null
          keywords_field: string | null
          promotional_text: string | null
          version: string | null
          snapshot_at: string
          created_at: string
        }
        Insert: {
          id?: string
          app_id: string
          locale?: string
          title?: string | null
          subtitle?: string | null
          description?: string | null
          keywords_field?: string | null
          promotional_text?: string | null
          version?: string | null
          snapshot_at?: string
          created_at?: string
        }
        Update: {
          title?: string | null
          subtitle?: string | null
          description?: string | null
          keywords_field?: string | null
          promotional_text?: string | null
          version?: string | null
        }
        Relationships: []
      }
      app_rankings_daily: {
        Row: {
          id: string
          app_id: string
          date: string
          country: string
          category: string | null
          rank_overall: number | null
          rank_category: number | null
          created_at: string
        }
        Insert: {
          id?: string
          app_id: string
          date: string
          country?: string
          category?: string | null
          rank_overall?: number | null
          rank_category?: number | null
          created_at?: string
        }
        Update: {
          rank_overall?: number | null
          rank_category?: number | null
        }
        Relationships: []
      }
      app_installs_estimate: {
        Row: {
          id: string
          app_id: string
          date: string
          country: string
          downloads_low: number | null
          downloads_high: number | null
          created_at: string
        }
        Insert: {
          id?: string
          app_id: string
          date: string
          country?: string
          downloads_low?: number | null
          downloads_high?: number | null
          created_at?: string
        }
        Update: {
          downloads_low?: number | null
          downloads_high?: number | null
        }
        Relationships: []
      }
      analysis_results: {
        Row: {
          id: string
          app_id: string
          organization_id: string
          analysis_type: string
          result: Record<string, unknown>
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          app_id: string
          organization_id: string
          analysis_type: string
          result: Record<string, unknown>
          created_at?: string
          updated_at?: string
        }
        Update: {
          result?: Record<string, unknown>
          updated_at?: string
        }
        Relationships: []
      }
      posts: {
        Row: {
          id: string
          type: string
          title: string
          slug: string
          excerpt: string | null
          content: string
          cover_image: string | null
          author_name: string | null
          status: string
          tags: string[]
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          type?: string
          title: string
          slug: string
          excerpt?: string | null
          content?: string
          cover_image?: string | null
          author_name?: string | null
          status?: string
          tags?: string[]
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          type?: string
          title?: string
          slug?: string
          excerpt?: string | null
          content?: string
          cover_image?: string | null
          author_name?: string | null
          status?: string
          tags?: string[]
          published_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      social_media_posts: {
        Row: {
          id: string
          platform: string
          content: string
          status: string
          hashtags: string[]
          image_prompt: string | null
          scheduled_at: string | null
          published_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          platform: string
          content?: string
          status?: string
          hashtags?: string[]
          image_prompt?: string | null
          scheduled_at?: string | null
          published_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          platform?: string
          content?: string
          status?: string
          hashtags?: string[]
          image_prompt?: string | null
          scheduled_at?: string | null
          published_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      admin_settings: {
        Row: {
          id: string
          key: string
          value: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          key: string
          value?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          key?: string
          value?: string
          updated_at?: string
        }
        Relationships: []
      }
      email_log: {
        Row: {
          id: string
          resend_id: string | null
          recipient_email: string
          subject: string
          email_type: string
          status: string
          error_message: string | null
          sent_at: string
          delivered_at: string | null
        }
        Insert: {
          id?: string
          resend_id?: string | null
          recipient_email: string
          subject: string
          email_type: string
          status?: string
          error_message?: string | null
          sent_at?: string
          delivered_at?: string | null
        }
        Update: {
          resend_id?: string | null
          status?: string
          error_message?: string | null
          delivered_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      plan_tier: 'solo' | 'team' | 'enterprise'
      org_role: 'owner' | 'admin' | 'member' | 'viewer'
      platform: 'ios' | 'android'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
